name: Testing

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  phpunit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        laravel: [9.*, 8.*, 7.*, 6.*, 5.7.*, 5.6.*, 5.5.*]
        dependency-version: [prefer-stable]
        os: [ubuntu-latest]
        include:
          - laravel: 9.*
            testbench: 7.*
            php: 8.0.2
          - laravel: 8.*
            testbench: 6.*
            php: 8.0
          - laravel: 7.*
            testbench: 5.*
            php: 7.2.5
          - laravel: 6.*
            testbench: 4.*
            php: 7.2.5
          - laravel: 5.7.*
            testbench: 3.7.*
            php: 7.1.3
          - laravel: 5.6.*
            testbench: 3.6.*
            php: 7.1.3
          - laravel: 5.5.*
            testbench: 3.5.*
            php: 7.0
      fail-fast: false

    steps:
    - name: Setup code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, dom, fileinfo, mysql, libxml, xml, xmlwriter, dom, tokenizer, filter, json, phar, pcre, openssl, pdo, intl, curl
        coverage: none

    - name: Install dependencies
      run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" predis/predis --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

    - name: Execute tests via PHPUnit
      run: vendor/bin/phpunit
